### PR TITLE
Support XS6

### PR DESCRIPTION
**Pull request by rdavisau**
_(Not ready to merge!)_

This PR aims to update Continuous to support XS6 by making the changes required to support the new Roslyn based architecture. It addresses #43. As I understand it, we need to do the following: 
- [x] Update non-core code to be compatible with changes in the v6 IDE apis
- [x] Modify the `ContinuousEnv.MonoDevelop.cs` file to add Rosyln-based type identification
- [x] Modify the `ContinuousEnv.MonoDevelop.cs` file to add Roslyn-based watch expression functionality
- [ ] Test it all properly, make sure things still work as expected 
- [x] Check this doesn't break the VS side of things 

To get it up and running, I skipped the watch expression functionality, so at this point we have working live-reload that I have tested in basic scenarios. I will look to add back the watch functionality and test it in more complicated ways in the coming days; to me it all looks pretty achievable. 

With XS6 support we will finally have the holy grail -- live reload + dark theme support. The future really is now! ✨

### CODE REVIEW

**Comment by rdavisau** [comment]
Naively I had ignored the dependency identification problem and that became clear after some testing 🚑. I have added that in - with a potentially controversial deviation from the original. The "dependencies" are taken at the document root, rather than within declaration. This is incorrect (not all the types identified are dependencies), but in testing it results in a more resilient/longer lived coding session because adding new files or classes does not require a reload. I don't believe this was possible previously without nesting the class in an already 'known' class. 

I haven't noticed any issues with this less targeted approach; but I'll keep testing to see whether it is a reasonable change to make. Also interested in your views on it!

**Comment by SmartyP** [comment]
Is this in a usable state currently with XS6?

**Comment by rdavisau** [comment]
Howdyi - I just pushed a change to the version of XS that the addin targets - with that you can build this branch and install the add in manually. I use it most days. Because of the comment above, it is a little 'greedier' than the XS5 version, but there is only one line to change in the source if you prefer the old behaviour.

**Comment by praeclarum** [comment]
❤️❤️❤️

**Pull request merged**
